# this is the build file for project SmartPawn
# it is autogenerated by the xmake build system.
# do not edit by hand.

MRC=C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\rc.exe
CC=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe
CXX=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe
AS=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\ml64.exe
FC=gfortran

AR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe
FCSH=gfortran
SH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe
FCLD=gfortran
LD=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe

SmartPawnViewer_CXXFLAGS=/EHsc -nologo -Zi -FS -Fdbin\windows_x64_release\compile.SmartPawnViewer.pdb -Ox -fp:fast -std:c++17 -MD -Isrc\SmartPawnViewer -Isrc\SPIntelligence -Isrc\SPEngine -DSP_PLATFORM_WIN -DSFML_STATIC -external:IC:\Users\romai\AppData\Local\.xmake\packages\s\spdlog\v1.9.0\9df96f2d10a146d38b87b2a4fca52faa\include -external:IC:\Users\romai\AppData\Local\.xmake\packages\s\sfml\2.5.1\e3f1dd9ec1724070a224c808a7d5c4eb\include -DNDEBUG
SmartPawnViewer_LDFLAGS=-nologo -dynamicbase -nxcompat -machine:x64 -libpath:C:\Users\romai\AppData\Local\.xmake\packages\s\sfml\2.5.1\e3f1dd9ec1724070a224c808a7d5c4eb\lib -libpath:bin\windows_x64_release /opt:ref /opt:icf -debug -pdb:bin\windows_x64_release\SmartPawnViewer.pdb flac.lib freetype.lib ogg.lib openal32.lib sfml-audio-s.lib sfml-graphics-s.lib sfml-main.lib sfml-network-s.lib sfml-system-s.lib sfml-window-s.lib vorbis.lib vorbisenc.lib vorbisfile.lib SPEngine.lib opengl32.lib gdi32.lib user32.lib advapi32.lib ws2_32.lib winmm.lib
SPIntelligence_CXXFLAGS=/EHsc -nologo -Zi -FS -Fdbin\windows_x64_release\compile.SPIntelligence.pdb -Ox -fp:fast -std:c++17 -MD -Isrc\SPIntelligence -Isrc\SPEngine -DSP_PLATFORM_WIN -DSFML_STATIC -external:IC:\Users\romai\AppData\Local\.xmake\packages\s\spdlog\v1.9.0\9df96f2d10a146d38b87b2a4fca52faa\include -external:IC:\Users\romai\AppData\Local\.xmake\packages\s\sfml\2.5.1\e3f1dd9ec1724070a224c808a7d5c4eb\include -DNDEBUG
SPIntelligence_SHFLAGS=-nologo -machine:x64 -libpath:C:\Users\romai\AppData\Local\.xmake\packages\s\sfml\2.5.1\e3f1dd9ec1724070a224c808a7d5c4eb\lib -libpath:bin\windows_x64_release /opt:ref /opt:icf -debug -pdb:bin\windows_x64_release\SPIntelligence.pdb flac.lib freetype.lib ogg.lib openal32.lib sfml-audio-s.lib sfml-graphics-s.lib sfml-main.lib sfml-network-s.lib sfml-system-s.lib sfml-window-s.lib vorbis.lib vorbisenc.lib vorbisfile.lib SPEngine.lib opengl32.lib gdi32.lib user32.lib advapi32.lib ws2_32.lib winmm.lib
SPEngine_CXXFLAGS=/EHsc -nologo -Zi -FS -Fdbin\windows_x64_release\compile.SPEngine.pdb -Ox -fp:fast -std:c++17 -MD -Isrc\SPEngine -DSP_PLATFORM_WIN -DDLL_EXPORT -DSFML_STATIC -external:IC:\Users\romai\AppData\Local\.xmake\packages\s\spdlog\v1.9.0\9df96f2d10a146d38b87b2a4fca52faa\include -external:IC:\Users\romai\AppData\Local\.xmake\packages\s\sfml\2.5.1\e3f1dd9ec1724070a224c808a7d5c4eb\include -DNDEBUG
SPEngine_SHFLAGS=-nologo -machine:x64 -libpath:C:\Users\romai\AppData\Local\.xmake\packages\s\sfml\2.5.1\e3f1dd9ec1724070a224c808a7d5c4eb\lib /opt:ref /opt:icf -debug -pdb:bin\windows_x64_release\SPEngine.pdb flac.lib freetype.lib ogg.lib openal32.lib sfml-audio-s.lib sfml-graphics-s.lib sfml-main.lib sfml-network-s.lib sfml-system-s.lib sfml-window-s.lib vorbis.lib vorbisenc.lib vorbisfile.lib opengl32.lib gdi32.lib user32.lib advapi32.lib ws2_32.lib winmm.lib

default:  SmartPawnViewer SPIntelligence SPEngine

all:  SmartPawnViewer SPIntelligence SPEngine

.PHONY: default all  SmartPawnViewer SPIntelligence SPEngine

SmartPawnViewer: bin\windows_x64_release\SmartPawnViewer.exe
bin\windows_x64_release\SmartPawnViewer.exe: bin\windows_x64_release\SPEngine.dll build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core\Application.cpp.obj build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core\Logger.cpp.obj build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core\pch.cpp.obj build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\GUI\Button.cpp.obj build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\GUI\ProgressBar.cpp.obj build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Main.cpp.obj build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States\MenuState.cpp.obj build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States\SimGameState.cpp.obj build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States\State.cpp.obj
	@echo linking.release SmartPawnViewer.exe
	-@mkdir bin\windows_x64_release > NUL 2>&1
	@"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe" $(SmartPawnViewer_LDFLAGS) -out:bin\windows_x64_release\SmartPawnViewer.exe build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core\Application.cpp.obj build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core\Logger.cpp.obj build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core\pch.cpp.obj build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\GUI\Button.cpp.obj build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\GUI\ProgressBar.cpp.obj build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Main.cpp.obj build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States\MenuState.cpp.obj build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States\SimGameState.cpp.obj build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States\State.cpp.obj > build/.build.log 2>&1

build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core\Application.cpp.obj: src\SmartPawnViewer\Core\Application.cpp
	@echo compiling.release src\SmartPawnViewer\Core\Application.cpp
	-@mkdir build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core > NUL 2>&1
	@"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" -c $(SmartPawnViewer_CXXFLAGS) -experimental:external -external:W0 -experimental:external -external:W0 -Fobuild\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core\Application.cpp.obj src\SmartPawnViewer\Core\Application.cpp > build/.build.log 2>&1

build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core\Logger.cpp.obj: src\SmartPawnViewer\Core\Logger.cpp
	@echo compiling.release src\SmartPawnViewer\Core\Logger.cpp
	-@mkdir build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core > NUL 2>&1
	@"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" -c $(SmartPawnViewer_CXXFLAGS) -experimental:external -external:W0 -experimental:external -external:W0 -Fobuild\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core\Logger.cpp.obj src\SmartPawnViewer\Core\Logger.cpp > build/.build.log 2>&1

build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core\pch.cpp.obj: src\SmartPawnViewer\Core\pch.cpp
	@echo compiling.release src\SmartPawnViewer\Core\pch.cpp
	-@mkdir build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core > NUL 2>&1
	@"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" -c $(SmartPawnViewer_CXXFLAGS) -experimental:external -external:W0 -experimental:external -external:W0 -Fobuild\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core\pch.cpp.obj src\SmartPawnViewer\Core\pch.cpp > build/.build.log 2>&1

build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\GUI\Button.cpp.obj: src\SmartPawnViewer\GUI\Button.cpp
	@echo compiling.release src\SmartPawnViewer\GUI\Button.cpp
	-@mkdir build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\GUI > NUL 2>&1
	@"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" -c $(SmartPawnViewer_CXXFLAGS) -experimental:external -external:W0 -experimental:external -external:W0 -Fobuild\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\GUI\Button.cpp.obj src\SmartPawnViewer\GUI\Button.cpp > build/.build.log 2>&1

build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\GUI\ProgressBar.cpp.obj: src\SmartPawnViewer\GUI\ProgressBar.cpp
	@echo compiling.release src\SmartPawnViewer\GUI\ProgressBar.cpp
	-@mkdir build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\GUI > NUL 2>&1
	@"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" -c $(SmartPawnViewer_CXXFLAGS) -experimental:external -external:W0 -experimental:external -external:W0 -Fobuild\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\GUI\ProgressBar.cpp.obj src\SmartPawnViewer\GUI\ProgressBar.cpp > build/.build.log 2>&1

build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Main.cpp.obj: src\SmartPawnViewer\Main.cpp
	@echo compiling.release src\SmartPawnViewer\Main.cpp
	-@mkdir build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer > NUL 2>&1
	@"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" -c $(SmartPawnViewer_CXXFLAGS) -experimental:external -external:W0 -experimental:external -external:W0 -Fobuild\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Main.cpp.obj src\SmartPawnViewer\Main.cpp > build/.build.log 2>&1

build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States\MenuState.cpp.obj: src\SmartPawnViewer\States\MenuState.cpp
	@echo compiling.release src\SmartPawnViewer\States\MenuState.cpp
	-@mkdir build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States > NUL 2>&1
	@"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" -c $(SmartPawnViewer_CXXFLAGS) -experimental:external -external:W0 -experimental:external -external:W0 -Fobuild\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States\MenuState.cpp.obj src\SmartPawnViewer\States\MenuState.cpp > build/.build.log 2>&1

build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States\SimGameState.cpp.obj: src\SmartPawnViewer\States\SimGameState.cpp
	@echo compiling.release src\SmartPawnViewer\States\SimGameState.cpp
	-@mkdir build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States > NUL 2>&1
	@"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" -c $(SmartPawnViewer_CXXFLAGS) -experimental:external -external:W0 -experimental:external -external:W0 -Fobuild\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States\SimGameState.cpp.obj src\SmartPawnViewer\States\SimGameState.cpp > build/.build.log 2>&1

build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States\State.cpp.obj: src\SmartPawnViewer\States\State.cpp
	@echo compiling.release src\SmartPawnViewer\States\State.cpp
	-@mkdir build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States > NUL 2>&1
	@"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" -c $(SmartPawnViewer_CXXFLAGS) -experimental:external -external:W0 -experimental:external -external:W0 -Fobuild\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States\State.cpp.obj src\SmartPawnViewer\States\State.cpp > build/.build.log 2>&1

SPIntelligence: bin\windows_x64_release\SPIntelligence.dll
bin\windows_x64_release\SPIntelligence.dll: bin\windows_x64_release\SPEngine.dll build\.objs\SPIntelligence\windows\x64\release\src\SPIntelligence\SPBluePlugin.cpp.obj
	@echo linking.release SPIntelligence.dll
	-@mkdir bin\windows_x64_release > NUL 2>&1
	@"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe" -dll $(SPIntelligence_SHFLAGS) -out:bin\windows_x64_release\SPIntelligence.dll build\.objs\SPIntelligence\windows\x64\release\src\SPIntelligence\SPBluePlugin.cpp.obj > build/.build.log 2>&1

build\.objs\SPIntelligence\windows\x64\release\src\SPIntelligence\SPBluePlugin.cpp.obj: src\SPIntelligence\SPBluePlugin.cpp
	@echo compiling.release src\SPIntelligence\SPBluePlugin.cpp
	-@mkdir build\.objs\SPIntelligence\windows\x64\release\src\SPIntelligence > NUL 2>&1
	@"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" -c $(SPIntelligence_CXXFLAGS) -experimental:external -external:W0 -experimental:external -external:W0 -Fobuild\.objs\SPIntelligence\windows\x64\release\src\SPIntelligence\SPBluePlugin.cpp.obj src\SPIntelligence\SPBluePlugin.cpp > build/.build.log 2>&1

SPEngine: bin\windows_x64_release\SPEngine.dll
bin\windows_x64_release\SPEngine.dll: build\.objs\SPEngine\windows\x64\release\src\SPEngine\Engine\SimEngine.cpp.obj build\.objs\SPEngine\windows\x64\release\src\SPEngine\Engine\SPPlugin.cpp.obj
	@echo linking.release SPEngine.dll
	-@mkdir bin\windows_x64_release > NUL 2>&1
	@"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe" -dll $(SPEngine_SHFLAGS) -out:bin\windows_x64_release\SPEngine.dll build\.objs\SPEngine\windows\x64\release\src\SPEngine\Engine\SimEngine.cpp.obj build\.objs\SPEngine\windows\x64\release\src\SPEngine\Engine\SPPlugin.cpp.obj > build/.build.log 2>&1

build\.objs\SPEngine\windows\x64\release\src\SPEngine\Engine\SimEngine.cpp.obj: src\SPEngine\Engine\SimEngine.cpp
	@echo compiling.release src\SPEngine\Engine\SimEngine.cpp
	-@mkdir build\.objs\SPEngine\windows\x64\release\src\SPEngine\Engine > NUL 2>&1
	@"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" -c $(SPEngine_CXXFLAGS) -experimental:external -external:W0 -experimental:external -external:W0 -Fobuild\.objs\SPEngine\windows\x64\release\src\SPEngine\Engine\SimEngine.cpp.obj src\SPEngine\Engine\SimEngine.cpp > build/.build.log 2>&1

build\.objs\SPEngine\windows\x64\release\src\SPEngine\Engine\SPPlugin.cpp.obj: src\SPEngine\Engine\SPPlugin.cpp
	@echo compiling.release src\SPEngine\Engine\SPPlugin.cpp
	-@mkdir build\.objs\SPEngine\windows\x64\release\src\SPEngine\Engine > NUL 2>&1
	@"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" -c $(SPEngine_CXXFLAGS) -experimental:external -external:W0 -experimental:external -external:W0 -Fobuild\.objs\SPEngine\windows\x64\release\src\SPEngine\Engine\SPPlugin.cpp.obj src\SPEngine\Engine\SPPlugin.cpp > build/.build.log 2>&1

clean:  clean_SmartPawnViewer clean_SPIntelligence clean_SPEngine

clean_SmartPawnViewer:  clean_SPEngine
	@del /F /Q bin\windows_x64_release\SmartPawnViewer.exe > NUL 2>&1 || rmdir /S /Q bin\windows_x64_release\SmartPawnViewer.exe > NUL 2>&1
	@del /F /Q bin\windows_x64_release\SmartPawnViewer.pdb > NUL 2>&1 || rmdir /S /Q bin\windows_x64_release\SmartPawnViewer.pdb > NUL 2>&1
	@del /F /Q build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core\Application.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core\Application.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core\Logger.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core\Logger.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core\pch.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Core\pch.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\GUI\Button.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\GUI\Button.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\GUI\ProgressBar.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\GUI\ProgressBar.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Main.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\Main.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States\MenuState.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States\MenuState.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States\SimGameState.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States\SimGameState.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States\State.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\SmartPawnViewer\windows\x64\release\src\SmartPawnViewer\States\State.cpp.obj > NUL 2>&1

clean_SPIntelligence:  clean_SPEngine
	@del /F /Q bin\windows_x64_release\SPIntelligence.dll > NUL 2>&1 || rmdir /S /Q bin\windows_x64_release\SPIntelligence.dll > NUL 2>&1
	@del /F /Q bin\windows_x64_release\SPIntelligence.pdb > NUL 2>&1 || rmdir /S /Q bin\windows_x64_release\SPIntelligence.pdb > NUL 2>&1
	@del /F /Q build\.objs\SPIntelligence\windows\x64\release\src\SPIntelligence\SPBluePlugin.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\SPIntelligence\windows\x64\release\src\SPIntelligence\SPBluePlugin.cpp.obj > NUL 2>&1

clean_SPEngine: 
	@del /F /Q bin\windows_x64_release\SPEngine.dll > NUL 2>&1 || rmdir /S /Q bin\windows_x64_release\SPEngine.dll > NUL 2>&1
	@del /F /Q bin\windows_x64_release\SPEngine.pdb > NUL 2>&1 || rmdir /S /Q bin\windows_x64_release\SPEngine.pdb > NUL 2>&1
	@del /F /Q build\.objs\SPEngine\windows\x64\release\src\SPEngine\Engine\SimEngine.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\SPEngine\windows\x64\release\src\SPEngine\Engine\SimEngine.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\SPEngine\windows\x64\release\src\SPEngine\Engine\SPPlugin.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\SPEngine\windows\x64\release\src\SPEngine\Engine\SPPlugin.cpp.obj > NUL 2>&1

